name: Build & Deploy — Dev

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build tag version
        id: tag-version
        run: echo "version=${{ github.run_number }}-${GITHUB_SHA::7}" >> "$GITHUB_OUTPUT"

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Test
        run: dotnet test --no-build

      - name: Publish
        run: dotnet publish -c Release -o publish --no-build

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            -f deployment/Dockerfile.dev \
            -t ghcr.io/zawthanoo/payment-service:${{ steps.tag-version.outputs.version }} \
            .

      - name: Push Docker Image
        run: docker push ghcr.io/zawthanoo/payment-service:${{ steps.tag-version.outputs.version }}

      - name: Checkout Kustomize chart Repository
        uses: actions/checkout@v4
        with:
          repository: zawthanoo/workshop-apps
          path: deployment
          token: ${{ secrets.MY_GITHUB_TOKEN }}

      # - name: Update image tag in dev overlay
      #   uses: fjogeleit/yaml-update-action@main
      #   with:
      #     repository: zawthanoo/workshop-apps
      #     valueFile: payment-service/overlays/dev/kustomization.yaml
      #     branch: main
      #     createPR: "false"
      #     message: "payment-service dev release for workshop"
      #     token: ${{ secrets.MY_GITHUB_TOKEN }}
      #     workDir: deployment
      #     changes: |
      #       {
      #         "images[0].newTag": "${{ steps.tag-version.outputs.version }}"
      #       }
